"""
Compares the openEHR archetype leaf inventory against the capacity of the OMOP CDM tables
the archetypes map into, to support the manuscript's claim that archetypes carry far more
data nodes than their target OMOP tables can hold.

What it does, in plain terms:
  There are two sides to the comparison, kept clearly apart below.

  ARCHETYPE SIDE  what openEHR offers. Every archetype has a number of "leaves": its data
                  elements plus its cluster slots. That is how many distinct things the
                  archetype can record. Read from archetypes.csv.
  OMOP SIDE       what OMOP can accept. Every OMOP CDM table has been reduced to its
                  "content concepts": the columns that actually carry content, after
                  housekeeping columns (record ids, linkage fields, redundant
                  _source_value / _source_concept_id twins) are collapsed away. That is
                  how many distinct things the table can hold. Read from omoptables.csv.

  The two sides are joined through the OMOCL mapping files. Each mapping YAML names one
  archetype (`spec.openEhrConfig.archetype`) and lists the OMOP tables it writes into:

      mappings:
        - type: "Measurement"      <- this block writes a Measurement record
        - type: "Observation"      <- a second block, an Observation record

  An archetype's capacity is the widest table it maps into (the most content concepts any
  one of its target records can hold). Comparing leaves against that capacity shows how
  much of an archetype has no column to go to. This is deliberately a generous reading of
  OMOP: it credits the archetype with the best table it touches, and still the archetype
  is wider almost every time.

  Nothing here is estimated and nothing is hardcoded; every number printed is derived from
  the data sources below at run time.

Two conventions in the mapping files matter:
  - `type: Include` is an OMOCL directive (it plugs another archetype's mapping in), not an
    OMOP table, so it is excluded from the block counts entirely.
  - `type: CustomMapping` builds a fact_relationship row. It is a real mapping block and is
    counted as one, but Fact_relationship is pure linkage, has no prepared table, and so
    contributes no capacity.

Cross-check: section 4 counts the mapping blocks independently of
../Figure4Domains/domain_distribution.py, which counts the same blocks for Figure 4. The two
totals must agree. Run both; if they ever differ, one of them is wrong.

Data: ../resources/OMOCL mappings   (medical_data/** and person_data/**, tests excluded)
      ../resources/preparedArchetypeTables/preparedArchetypes/archetypes.csv
      ../resources/preparedOMOPTables/omoptables.csv
      ../T3Fragementation/resources/fragmentation.csv   (section 6 only; generated by
                                                         ../T3Fragementation/fragmentation.py,
                                                         which must be run first)
Requires: Python 3.7+ and PyYAML.   Run:  python "leaf_capacity_comparison.py"
"""
import os
import csv
import glob
import collections
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
RESOURCES = os.path.join(HERE, "..", "resources")

# OMOCL side: the mappings that join an archetype to its OMOP tables.
MAPPINGS_DIR = os.path.join(RESOURCES, "OMOCL mappings")
# Archetype side: how many leaves each archetype has.
ARCHETYPES_CSV = os.path.join(RESOURCES, "preparedArchetypeTables", "preparedArchetypes",
                              "archetypes.csv")
# OMOP side: how many content concepts each OMOP table can hold.
OMOP_TABLES_CSV = os.path.join(RESOURCES, "preparedOMOPTables", "omoptables.csv")

# Measured side, for section 6 only: what the mapping actually puts on the primary record.
# This is ../T3Fragementation's own output (Table 3), read here so the arithmetic floor and
# the measurement can be printed on one screen, over the same archetypes. Section 6 is
# skipped if it has not been generated.
FRAGMENTATION_CSV = os.path.join(HERE, "..", "T3Fragementation", "resources",
                                 "fragmentation.csv")

# "Include" plugs another archetype's mapping in at a base path. It reads like a block but
# names no OMOP table, so it is not a mapping block and is dropped before anything is counted.
NOT_A_TABLE = "Include"

# "CustomMapping" is how a fact_relationship row is built. It IS a mapping block (it is counted
# as one), but fact_relationship is linkage rather than content: it has no row in
# omoptables.csv, so an archetype that only reaches it has no capacity to compare against.
CUSTOM_MAPPING = "CustomMapping"
FACT_RELATIONSHIP = "Fact_relationship"

# A table this narrow can hold almost nothing; the concentration section counts how many
# mapping blocks aim at one.
NARROW_TABLE_CAPACITY = 5

# The leaf counts the distribution section reports "how many archetypes are wider than this".
LEAF_THRESHOLDS = (4, 5, 10, 20, 30)

# How many of the widest archetypes to list at the end.
WIDEST_ARCHETYPES_SHOWN = 10

# One archetype's row in the comparison: its leaves (archetype side) against the capacity of
# the tables its mapping targets (OMOP side). `capacity` is None when the mapping reaches no
# table that has a prepared capacity (fact_relationship only, or Include only).
ComparisonRow = collections.namedtuple(
    "ComparisonRow", "archetype elements slots leaves target_tables capacity")


# ================================================================================
# READ  -  the four data sources
# ================================================================================

def find_mapping_files():
    """Every OMOCL mapping YAML (medical_data + person_data), skipping the test fixtures."""
    paths = []
    for subfolder in ("medical_data", "person_data"):
        paths += glob.glob(os.path.join(MAPPINGS_DIR, subfolder, "**", "*.yml"), recursive=True)
    return sorted(path for path in paths if (os.sep + "tests" + os.sep) not in path)


def read_archetype_leaf_counts():
    """archetype id -> {elements, slots, leaves}, the archetype side of the comparison.

    From archetypes.csv, the vetted inventory: one row per archetype, `leaves` = the data
    elements plus the cluster slots it defines.
    """
    archetype_leaf_counts = collections.OrderedDict()
    with open(ARCHETYPES_CSV, encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            archetype_leaf_counts[row["archetype"]] = {
                "elements": int(row["elements"]),
                "slots": int(row["slots"]),
                "leaves": int(row["leaves"]),
            }
    return archetype_leaf_counts


def read_omop_table_capacity():
    """OMOP table -> content concepts it can hold, the OMOP side of the comparison.

    From omoptables.csv, where each CDM table has already been reduced to the columns that
    carry content (`removed` records how many were collapsed or dropped to get there).
    """
    omop_table_capacity = collections.OrderedDict()
    with open(OMOP_TABLES_CSV, encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            omop_table_capacity[row["table"]] = int(row["content_concepts"])
    return omop_table_capacity


def read_measured_fragmentation():
    """archetype id -> {leaves, mapped_primary}, or None if T3Fragementation has not run.

    The measured side of section 6: fragmentation.py reads the same prepared leaves, matches
    each one to the OMOCL mapping by its at-code, and records how many actually landed on the
    archetype's primary OMOP record. Everything else needs a separate record.
    """
    if not os.path.exists(FRAGMENTATION_CSV):
        return None
    measured = {}
    with open(FRAGMENTATION_CSV, encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            measured[row["archetype"]] = {
                "leaves": int(row["leaves"]),
                "mapped_primary": int(row["mapped_primary"]),
            }
    return measured


def read_mapping_targets(mapping_file):
    """One mapping YAML -> (archetype id it maps, [OMOP table per mapping block]).

    The table list keeps duplicates on purpose: an archetype that writes twelve Measurement
    records has twelve Measurement blocks, and the block count is what Figure 4 reports.
    """
    content = yaml.safe_load(open(mapping_file, encoding="utf-8")) or {}
    spec = content.get("spec") or {}
    archetype_id = (spec.get("openEhrConfig") or {}).get("archetype")

    target_tables = []
    for block in content.get("mappings", []) or []:
        if not isinstance(block, dict) or "type" not in block:
            continue
        block_type = block["type"]
        if block_type == NOT_A_TABLE:
            continue                                  # a directive, not a table
        target_tables.append(FACT_RELATIONSHIP if block_type == CUSTOM_MAPPING else block_type)
    return archetype_id, target_tables


# ================================================================================
# JOIN  -  every mapping file to its archetype, and to its tables' capacity
# ================================================================================

def build_comparison(archetype_leaf_counts, omop_table_capacity):
    """One ComparisonRow per mapping file, plus the list of files that failed to join.

    DATA QUIRK, not a general rule: two mapping files spell the archetype id with different
    casing than the archetype inventory does
    (`openEHR-EHR-CLUSTER.Oocyte_specimen.v1`, `openEHR-EHR-Evaluation.pregnancy_status.v0`).
    openEHR archetype ids are otherwise case-consistent, so the case-insensitive lookup here
    exists only to absorb those two typos and let all 198 files join. Any file that still
    fails to join is returned and reported loudly by the caller, never dropped in silence.
    """
    canonical_id = {archetype.lower(): archetype for archetype in archetype_leaf_counts}

    comparison_rows = []
    unmatched_files = []
    unknown_tables = set()
    for mapping_file in find_mapping_files():
        mapping_archetype_id, target_tables = read_mapping_targets(mapping_file)
        archetype = canonical_id.get((mapping_archetype_id or "").lower())
        if archetype is None:
            unmatched_files.append((os.path.basename(mapping_file), mapping_archetype_id))
            continue

        # Fact_relationship is the ONLY table allowed to have no prepared capacity: it is
        # linkage and holds no content. Any other unknown table would be silently left out
        # of the max below, which would raise every capacity-based number in the archetype's
        # favour. Collected here and raised by the caller rather than quietly skipped.
        unknown_tables.update(set(target_tables) - set(omop_table_capacity)
                              - {FACT_RELATIONSHIP})

        # The archetype's capacity is the widest table it writes into: the most content
        # concepts any single one of its OMOP records can hold. Tables with no prepared
        # capacity (fact_relationship) cannot contribute one, so an archetype that reaches
        # nothing else has no capacity at all and is excluded from capacity comparisons.
        capacities = [omop_table_capacity[table] for table in target_tables
                      if table in omop_table_capacity]

        counts = archetype_leaf_counts[archetype]
        comparison_rows.append(ComparisonRow(
            archetype=archetype,
            elements=counts["elements"],
            slots=counts["slots"],
            leaves=counts["leaves"],
            target_tables=target_tables,
            capacity=max(capacities) if capacities else None,
        ))
    comparison_rows.sort(key=lambda row: row.archetype)
    return comparison_rows, unmatched_files, unknown_tables


# ================================================================================
# SUMMARISE  -  the small statistics the sections need
# ================================================================================

def percentile(sorted_values, fraction):
    """The value at `fraction` (0.0 = minimum, 1.0 = maximum) of an already sorted list.

    The script targets Python 3.7, where statistics.quantiles does not exist yet, so the
    rule is spelled out: land on a position between the first and last item and interpolate
    linearly between the two neighbouring data points. This is the same "inclusive" rule
    numpy and later Python versions use, so the numbers are comparable.
    """
    if not sorted_values:
        return float("nan")
    position = fraction * (len(sorted_values) - 1)
    lower_index = int(position)
    upper_index = min(lower_index + 1, len(sorted_values) - 1)
    weight = position - lower_index
    return sorted_values[lower_index] * (1.0 - weight) + sorted_values[upper_index] * weight


def mean(values):
    return float(sum(values)) / len(values) if values else float("nan")


def median(values):
    return percentile(sorted(values), 0.5)


def percentage(part, whole):
    return 100.0 * part / whole if whole else float("nan")


# ================================================================================
# REPORT  -  the six sections, each printed from the joined data
# ================================================================================

def print_aggregate(comparison_rows, omop_table_capacity):
    """Section 1: the size of each side. Inventory only, deliberately not a ratio.

    The two totals are NOT divided into each other. The archetype total counts nodes across
    198 separate artifacts; the OMOP total counts columns across 10 table definitions. A
    ratio between them would measure "198 > 10" rather than any loss of information, since
    OMOP is free to write unlimited rows into a table. The comparison that carries meaning
    is per archetype, against the table its own mapping reaches: section 2.
    """
    total_elements = sum(row.elements for row in comparison_rows)
    total_slots = sum(row.slots for row in comparison_rows)
    total_leaves = sum(row.leaves for row in comparison_rows)
    total_capacity = sum(omop_table_capacity.values())

    print("=" * 78)
    print("1. INVENTORY  -  the size of each side (context for section 2, not a claim)")
    print("=" * 78)
    print("archetypes mapped                 : %d" % len(comparison_rows))
    print("  data elements                   : %d" % total_elements)
    print("  cluster slots                   : %d" % total_slots)
    print("  leaves (elements + slots)       : %d" % total_leaves)
    print("OMOP tables prepared              : %d" % len(omop_table_capacity))
    print("  content concepts (total)        : %d" % total_capacity)


def print_per_archetype(comparison_rows):
    """Section 2: each archetype against the widest table its own mapping reaches."""
    with_capacity = [row for row in comparison_rows if row.capacity is not None]
    without_capacity = [row for row in comparison_rows if row.capacity is None]

    over_capacity = [row for row in with_capacity if row.leaves > row.capacity]
    leaves = [row.leaves for row in with_capacity]
    capacities = [row.capacity for row in with_capacity]

    print()
    print("=" * 78)
    print("2. PER ARCHETYPE  -  leaves against the capacity of its own target table")
    print("=" * 78)
    print("(capacity = the most content concepts any single table the archetype maps into")
    print(" can hold, i.e. the most generous table available to it)")
    print()
    print("archetypes with a target capacity : %d" % len(with_capacity))
    print("  more leaves than capacity       : %d  (%.1f%%)"
          % (len(over_capacity), percentage(len(over_capacity), len(with_capacity))))
    print("  leaves     median / mean        : %.1f / %.1f" % (median(leaves), mean(leaves)))
    print("  capacity   median / mean        : %.1f / %.1f"
          % (median(capacities), mean(capacities)))
    print("  summed leaves vs summed capacity: %d vs %d  (%.1f x)"
          % (sum(leaves), sum(capacities), float(sum(leaves)) / sum(capacities)))

    # Not a silent drop: these archetypes reach no table with a prepared capacity, so there
    # is nothing to compare them against. They are named so the gap is visible, not hidden.
    if without_capacity:
        print()
        print("archetypes with no target capacity: %d  (excluded from the comparison above;"
              % len(without_capacity))
        print("  their mapping reaches no prepared table)")
        for row in without_capacity:
            targets = ", ".join(sorted(set(row.target_tables))) or "no table (Include only)"
            print("    %-58s %d leaves -> %s" % (row.archetype, row.leaves, targets))


def print_per_omop_table(comparison_rows, omop_table_capacity):
    """Section 3: the load each OMOP table is asked to carry."""
    blocks_per_table = collections.Counter()
    archetypes_per_table = collections.defaultdict(set)

    for row in comparison_rows:
        for table in row.target_tables:
            blocks_per_table[table] += 1
        for table in set(row.target_tables):
            archetypes_per_table[table].add(row.archetype)

    print()
    print("=" * 78)
    print("3. PER OMOP TABLE  -  where the mapping load lands")
    print("=" * 78)
    print("%-22s %9s %8s %11s" % ("Table", "Capacity", "Blocks", "Archetypes"))
    print("-" * 53)
    for table, block_count in sorted(blocks_per_table.items(),
                                     key=lambda pair: pair[1], reverse=True):
        capacity = omop_table_capacity.get(table)
        print("%-22s %9s %8d %11d"
              % (table,
                 capacity if capacity is not None else "-",     # fact_relationship holds no content
                 block_count,
                 len(archetypes_per_table[table])))
    print("-" * 53)
    print("%-22s %9d %8d %11d" % ("total", sum(omop_table_capacity.values()),
                                  sum(blocks_per_table.values()),
                                  len(comparison_rows)))
    print()
    multi_table = sum(1 for row in comparison_rows if len(set(row.target_tables)) > 1)
    print("Deliberately no leaf column here. Totalling the leaves of every archetype that")
    print("targets a table would count the %d multi-table archetypes once per table, and"
          % multi_table)
    print("comparing that total to a single row's capacity would compare an inventory to a")
    print("row width. Leaves are compared per archetype in section 2, where they belong.")


def print_concentration(comparison_rows, omop_table_capacity):
    """Section 4: how much of the mapping is funnelled into the narrowest tables."""
    total_blocks = sum(len(row.target_tables) for row in comparison_rows)
    # Membership is tested FIRST: fact_relationship has no prepared capacity, and a table
    # with no known width is not evidence of a narrow one. It counts in total_blocks (it is
    # a real mapping block) but can never count as narrow.
    narrow_blocks = sum(1
                        for row in comparison_rows
                        for table in row.target_tables
                        if table in omop_table_capacity
                        and omop_table_capacity[table] <= NARROW_TABLE_CAPACITY)

    print()
    print("=" * 78)
    print("4. CONCENTRATION  -  how many mapping blocks land in a very narrow table")
    print("=" * 78)
    print("mapping blocks (total)            : %d" % total_blocks)
    print("  targeting a table with <= %d     : %d  (%.1f%%)"
          % (NARROW_TABLE_CAPACITY, narrow_blocks, percentage(narrow_blocks, total_blocks)))
    print("  content concepts")
    print()
    print("Cross-check: this block total is computed independently of, and must agree with,")
    print("the total ../Figure4Domains/domain_distribution.py prints for Figure 4. Run both")
    print("and compare; if they differ, one of them is wrong.")


def print_leaf_distribution(comparison_rows):
    """Section 5: the shape of the archetype side, and the extreme cases."""
    sorted_leaves = sorted(row.leaves for row in comparison_rows)

    print()
    print("=" * 78)
    print("5. DISTRIBUTION  -  leaves per archetype")
    print("=" * 78)
    print("min / p25 / median / p75 / max     : %d / %.1f / %.1f / %.1f / %d"
          % (sorted_leaves[0], percentile(sorted_leaves, 0.25), percentile(sorted_leaves, 0.50),
             percentile(sorted_leaves, 0.75), sorted_leaves[-1]))
    print()
    print("archetypes with more leaves than:")
    for threshold in LEAF_THRESHOLDS:
        above = sum(1 for leaves in sorted_leaves if leaves > threshold)
        print("  %2d leaves                       : %3d  (%.1f%%)"
              % (threshold, above, percentage(above, len(sorted_leaves))))

    widest = sorted(comparison_rows, key=lambda row: row.leaves,
                    reverse=True)[:WIDEST_ARCHETYPES_SHOWN]
    print()
    print("the %d widest archetypes:" % len(widest))
    print("%-52s %7s %9s %7s" % ("Archetype", "Leaves", "Capacity", "Ratio"))
    print("-" * 78)
    for row in widest:
        if row.capacity is not None:
            capacity_text = "%d" % row.capacity
            ratio_text = "%.1fx" % (float(row.leaves) / row.capacity)
        else:
            capacity_text, ratio_text = "-", "-"      # no prepared table to compare against
        print("%-52s %7d %9s %7s" % (row.archetype, row.leaves, capacity_text, ratio_text))


def print_arithmetic_floor(comparison_rows, measured_fragmentation):
    """Section 6: how much of the measured fragmentation is forced by counting alone.

    Why this section exists. The obvious objection to the measured fragmentation is that it
    is an artefact of how we chose to map, i.e. that a better mapping would keep more nodes
    on the primary record. This section answers that without using the mapping at all.

    Count an archetype's nodes, count the content fields of the table it targets, and assume
    -- generously, and counterfactually -- that ANY node could occupy ANY field. Whatever is
    left over has no field to go to under any mapping whatsoever. That is a floor: no mapping
    decision can push fragmentation below it.

    Both numbers answer the SAME question (what fits on one primary record?) over the SAME
    archetypes, which is what makes them comparable: the floor answers it by counting fields,
    fragmentation.py answers it by reading the mapping. The floor must come out at or below
    the measurement.

    What the gap between them is NOT. This script does not measure why the gap exists and no
    claim about its cause can be read out of these numbers. Two candidates are indistinguish-
    able here: OMOP's fields are typed, so a Severity node cannot occupy condition_start_date
    even when that column is empty; and a mapping may leave a usable field unused. Only the
    floor itself is established, and only as a lower bound.

    This is a lower bound, NOT an estimate of fragmentation. It sits well below the measured
    value by construction, and reporting it as a prediction would misrepresent it. What it
    supports is one bounded claim: at least this share of the fragmentation is forced by the
    size difference alone and holds under any mapping whatsoever.
    """
    with_capacity = [row for row in comparison_rows if row.capacity is not None]

    total_nodes = sum(row.leaves for row in with_capacity)
    total_fields = sum(row.capacity for row in with_capacity)
    # Per archetype, because capacity is per archetype: a field can only hold a node of the
    # archetype whose record it belongs to. Summing first would let one archetype's spare
    # columns absorb another archetype's overflow, which no mapping could ever do.
    coverable = sum(min(row.leaves, row.capacity) for row in with_capacity)
    excess = sum(max(0, row.leaves - row.capacity) for row in with_capacity)

    print()
    print("=" * 78)
    print("6. ARITHMETIC FLOOR  -  fragmentation forced by size alone, before any mapping")
    print("=" * 78)
    print("(assumes any node could occupy any field, which no real mapping achieves;")
    print(" whatever still does not fit cannot fit under ANY mapping)")
    print()
    print("archetypes compared               : %d" % len(with_capacity))
    print("  archetype nodes                 : %d" % total_nodes)
    print("  content fields available        : %d" % total_fields)
    print("  nodes a field could cover       : %d  (%.1f%%)"
          % (coverable, percentage(coverable, total_nodes)))
    print("  nodes MORE than OMOP can cover  : %d  (%.1f%%)   <- the floor"
          % (excess, percentage(excess, total_nodes)))

    if measured_fragmentation is None:
        print()
        print("Measured comparison skipped: ../T3Fragementation/resources/fragmentation.csv")
        print("has not been generated. Run ../T3Fragementation/fragmentation.py first.")
        return

    # SAME ARCHETYPES ON BOTH SIDES. The whole section rests on the two numbers sharing a
    # denominator: the corpus-wide Table 3 figure is over all 198 archetypes, and comparing
    # that to a floor over 196 would be exactly the units error this comparison exists to
    # avoid. So the floor is recomputed over the archetypes the measurement also covers,
    # rather than trusting that the two sets happen to coincide.
    comparable = [row for row in with_capacity if row.archetype in measured_fragmentation]

    # No silent subsetting. If fragmentation.csv does not cover every archetype compared
    # above, the section would quietly compare a subset and still print a conclusion that
    # reads as though it covered them all -- internally consistent, and wrong.
    uncovered = [row.archetype for row in with_capacity if row.archetype not in measured_fragmentation]
    if uncovered:
        raise ValueError(
            "fragmentation.csv is missing %d of the %d archetypes compared above (e.g. %s). "
            "It is stale or incomplete: re-run ../T3Fragementation/fragmentation.py. "
            "Comparing only the archetypes it happens to cover would silently narrow the "
            "claim while still printing it as though it held for all of them."
            % (len(uncovered), len(with_capacity), ", ".join(sorted(uncovered)[:3])))

    floor_nodes = sum(row.leaves for row in comparable)
    floor_excess = sum(max(0, row.leaves - row.capacity) for row in comparable)
    measured_nodes = sum(measured_fragmentation[row.archetype]["leaves"] for row in comparable)
    measured_primary = sum(measured_fragmentation[row.archetype]["mapped_primary"]
                           for row in comparable)
    measured_auxiliary = measured_nodes - measured_primary

    floor_percentage = percentage(floor_excess, floor_nodes)
    measured_percentage = percentage(measured_auxiliary, measured_nodes)

    # Both invariants are checked BEFORE anything is printed. A failing invariant means the
    # numbers are not fit to publish, and printing the conclusion prose first would put a
    # false claim into a reviewer's log even though the run later aborts.
    if floor_nodes != measured_nodes:
        raise ValueError(
            "the two sides disagree about the node count over the same %d archetypes "
            "(floor %d, measured %d): archetypes.csv and fragmentation.csv have drifted "
            "apart, so neither number should be published."
            % (len(comparable), floor_nodes, measured_nodes))
    if floor_percentage > measured_percentage:
        raise ValueError(
            "arithmetic floor (%.1f%%) exceeds measured fragmentation (%.1f%%): the two "
            "sides disagree about what fits on a primary record, so one of them is wrong."
            % (floor_percentage, measured_percentage))

    print()
    print("measured over the same %d archetypes (from T3Fragementation):" % len(comparable))
    print("  archetype nodes                 : %d" % measured_nodes)
    print("  mapped to the primary record    : %d  (%.1f%%)"
          % (measured_primary, percentage(measured_primary, measured_nodes)))
    print("  needing a separate record       : %d  (%.1f%%)"
          % (measured_auxiliary, measured_percentage))
    print()
    print("floor %.1f%%  <=  measured %.1f%%   (gap %.1f points)"
          % (floor_percentage, measured_percentage, measured_percentage - floor_percentage))
    print()
    print("The floor lies below the measurement, as it must. At least %.1f of the %.1f measured"
          % (floor_percentage, measured_percentage))
    print("points follow from the size difference between the two models alone: those nodes have")
    print("no field on the primary record under ANY mapping, so that share cannot be attributed")
    print("to mapping decisions. The remaining %.1f points are NOT attributed by this script -"
          % (measured_percentage - floor_percentage))
    print("distinguishing typed fields from fields left unused needs the per-field analysis in")
    print("../T3Fragementation, not this counting argument.")


# ================================================================================
# DRIVE  -  read, join, check, report
# ================================================================================

def main():
    archetype_leaf_counts = read_archetype_leaf_counts()      # archetype side
    omop_table_capacity = read_omop_table_capacity()          # OMOP side
    comparison_rows, unmatched_files, unknown_tables = build_comparison(archetype_leaf_counts,
                                                                        omop_table_capacity)

    # Join invariant: every mapping file must find its archetype. A file that does not join
    # would quietly shrink every number below, so this stops the run instead.
    if unmatched_files:
        raise ValueError(
            "%d mapping file(s) name an archetype that is not in archetypes.csv:\n  %s"
            % (len(unmatched_files),
               "\n  ".join("%s -> %r" % pair for pair in unmatched_files)))

    # Capacity invariant: every table the mappings target must have a prepared capacity, or
    # it drops out of the capacity calculation and inflates the result in the archetype's
    # favour. Only fact_relationship may legitimately be absent, and that is handled above.
    if unknown_tables:
        raise ValueError(
            "the mappings target %d OMOP table(s) with no row in omoptables.csv: %s. "
            "They would be silently ignored when computing capacity, which would overstate "
            "every result below."
            % (len(unknown_tables), ", ".join(sorted(unknown_tables))))

    print_aggregate(comparison_rows, omop_table_capacity)
    print_per_archetype(comparison_rows)
    print_per_omop_table(comparison_rows, omop_table_capacity)
    print_concentration(comparison_rows, omop_table_capacity)
    print_leaf_distribution(comparison_rows)
    print_arithmetic_floor(comparison_rows, read_measured_fragmentation())

    print()
    print("join check: %d mapping file(s) read, %d joined to an archetype, %d unmatched."
          % (len(comparison_rows), len(comparison_rows), len(unmatched_files)))


if __name__ == "__main__":
    main()
